windowrulev2 = opacity 1.0, fullscreen:1

# Waybar
layerrule = blur, waybar

# Kitty
#windowrule = opacity 0.5 override, class:(kitty)

# Scrcpy
windowrule = prop keepaspectratio, class:(scrcpy)
windowrule = opacity 1, class:(scrcpy)

# Games
windowrule = float, class:(Steam)
windowrule = fullscreen, initialTitle:^(Steam Big Picture Mode)$
windowrule = opacity 1, class:(steam_app_)(.*)
windowrule = opacity 0, initialTitle:(DropShadowWindow)
windowrule = prop noblur, initialTitle:(DropShadowWindow)
windowrule = prop nofocus, initialTitle:(DropShadowWindow)
windowrulev2 = workspace silent:special, class:^(steam_app_480)$, title:^()$
#windowrulev2 = nofocus, class:^(steam_app_480)$, title:^()$
windowrulev2 = workspace silent:9, initialClass:^(steam_app_480)$, title:^()$

#windowrulev2 = fullscreen, initialTitle:^(Forza Horizon 5)$

windowrulev2 = fullscreen, class:^(steam_app_0)$, initialTitle:^(.*)$

#windowrulev2 = idleinhibit focus, class:^(heroic)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

# Rofi
layerrule = blur, rofi
windowrule = stayfocused, class:(rofi)

# Polkit
windowrule = float, class:(lxqt-policykit)

# Clipse
windowrule = center, class:(clipse)
windowrule = float, class:(clipse)
windowrule = size 960 560 override, class:(clipse)

# QEMU 
windowrule = float, title:^(.*)(QEMU/KVM)$
#windowrule = size 1200 800 override, title:^(.*)(QEMU/KVM)$
windowrule = prop keepaspectratio, title:^(.*)(QEMU/KVM)$
windowrule = opacity 1, title:^(.*)(QEMU/KVM)$

# Picture in picture 
windowrule = float, title:^(Picture-in-Picture)$
windowrule = prop keepaspectratio, title:^(Picture-in-Picture)$
windowrule = opacity 1, title:^(Picture-in-Picture)$

# YouTube
windowrule = opacity 1, title:^(.*)( - YouTube)(.*)$

# VLC
windowrule = opacity 1, class:^(vlc)$

# tschuss
windowrule= float, class:(tschuss)
windowrule= move 0.5% 5%, class:(tschuss)
windowrule= stayfocused, class:(tschuss)

# Ollama Hypr
windowrule = float, class:(hypr-ollama)
windowrule = center, class:(hypr-ollama)
windowrule = size 960 560 override, class:(hypr-ollama)

# Blackout
windowrule = center, class:(blackout)
windowrule = float, class:(blackout)
windowrule = size 960 560 override, class:(blackout)

# Swaync
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
