# Execute on launch Hyprland
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

exec-once = wbg -s ~/Pictures/.current_wallpaper &
exec-once = clipse -listen &
exec-once = waybar &
exec-once = hypridle 
exec-once = /usr/bin/lxqt-policykit-agent &
exec-once = sleep 0.3 && swaync
#exec-once = $HOME/.config/hypr/scripts/bluetooth
