$UserConfigs = $HOME/.config/hypr/userConfigs

windowrule = opacity 0.8, title:(.*)

source= $UserConfigs/startup.conf
source= $UserConfigs/rules.conf
source= $UserConfigs/binds.conf
source= $UserConfigs/env.conf
source= $UserConfigs/animation.conf

source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
monitor=, 1920x1080@74.97,auto,auto, vrr, 1

general {
    gaps_in = 2.5
    gaps_out = 5
    border_size = 1
    col.active_border = $color4
    col.inactive_border = $color8

    layout = dwindle
}

cursor {
    inactive_timeout = 2
}


decoration {
    rounding = 5
    fullscreen_opacity = 1
    
    blur {
        enabled = true
        size = 6
        passes = 3
	ignore_opacity = true
	xray = false
	new_optimizations = true
    }
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

gestures {
    workspace_swipe = on
}

input {
    kb_layout = us,br
    kb_options = grp:alt_space_toggle
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
