foreground         #EBEADA
background         #0C1016

background_opacity 1
cursor             #BCC1B4

selection_foreground #7B898D
selection_background #95936F

active_tab_foreground     #0C1016
active_tab_background     #EBEADA
inactive_tab_foreground   #EBEADA
inactive_tab_background   #0C1016

active_border_color   #EBEADA
inactive_border_color #0C1016
bell_border_color     #5C666A

color0      	#22252A
color1		#94936F
color2		#6A726B
color3		#787D6C
color4		#86886E
color5		#94936F
color6		#95936F
color7		#DAD9C1
color8		#999887
color9		#7B898D
color10		#8D988F
color11		#A0A691
color12		#B3B592
color13		#C6C494
color14		#C6C494
color15		#DAD9C1
