$background = rgb(0C1016)
$foreground = rgb(EBEADA)
$color0 = rgb(22252A)
$color1 = rgb(5C666A)
$color2 = rgb(6A726B)
$color3 = rgb(787D6C)
$color4 = rgb(86886E)
$color5 = rgb(94936F)
$color6 = rgb(95936F)
$color7 = rgb(DAD9C1)
$color8 = rgb(999887)
$color9 = rgb(7B898D)
$color10 = rgb(8D988F)
$color11 = rgb(A0A691)
$color12 = rgb(B3B592)
$color13 = rgb(C6C494)
$color14 = rgb(C6C494)
$color15 = rgb(DAD9C1)
